FROM mcr.microsoft.com/windows/servercore:ltsc2019
# Doc - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops

WORKDIR /azp

COPY start.ps1 .

CMD powershell .\start.ps1